version: "3.7"
services:
    spark-master:
        image: spark-master:3.0.3
        container_name: spark-master
        hostname: spark-master
        ports:
            - "8080:8080"
            - "7077:7077"
            - "8889:8888"
            - "4040:4040"
        volumes:
            - ./codes:/notebooks
            - ./data:/data
        networks:
            spark-network:
                ipv4_address: 10.5.0.2
        environment:
            - "PYSPARK_DRIVER_PYTHON=jupyter"
            - "PYSPARK_DRIVER_PYTHON_OPTS=notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''"
            - "SPARK_LOCAL_IP=spark-master"
    spark-worker-1:
        image: spark-worker:3.0.3
        container_name: spark-worker-1
        hostname: spark-worker-1
        depends_on:
            - spark-master
        ports:
            - "8081:8081"
        volumes:
            - ./data:/data
        env_file: ./worker/spark-worker.sh
        environment:
            - "SPARK_LOCAL_IP=spark-worker-1"
        networks: 
            spark-network:
                ipv4_address: 10.5.0.3
    spark-worker-2:
        image: spark-worker:3.0.3
        container_name: spark-worker-2
        hostname: spark-worker-2
        depends_on:
            - spark-master
        ports:
            - "8082:8081"
        volumes:
            - ./data:/data
        env_file: ./worker/spark-worker.sh
        environment:
            - "SPARK_LOCAL_IP=spark-worker-2"
        networks:
            spark-network:
                ipv4_address: 10.5.0.4
    spark-worker-3:
        image: spark-worker:3.0.3
        container_name: spark-worker-3
        hostname: spark-worker-3
        depends_on:
            - spark-master
        ports:
            - "8083:8081"
        volumes:
            - ./data:/data
        env_file: ./worker/spark-worker.sh
        environment:
            - "SPARK_LOCAL_IP=spark-worker-3"
        networks:
            spark-network:
                ipv4_address: 10.5.0.5
    spark-worker-4:
        image: spark-worker:3.0.3
        container_name: spark-worker-4
        hostname: spark-worker-4
        depends_on:
            - spark-master
        ports:
            - "8084:8081"
        volumes:
            - ./data:/data
        env_file: ./worker/spark-worker.sh
        environment:
            - "SPARK_LOCAL_IP=spark-worker-4"
        networks:
            spark-network:
                ipv4_address: 10.5.0.6
networks:
    spark-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.5.0.0/16
